# Generated by Django 2.2.14 on 2020-07-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200717_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gjhuyuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hfhfhgf', models.BigIntegerField()),
            ],
        ),
    ]
